name: Linting Checks

on:
  workflow_dispatch:
  push:

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca #v6.0.1

      - name: Install project dependencies
        run: |
          uv sync
          source .venv/bin/activate

      - name: Run pre-commit
        run: pre-commit run --all-files
